version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simple-todo-backend
    ports:
      - "9000:9000"
    environment:
      - DB_PATH=/app/data.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simple-todo-frontend
    ports:
      - "5173:5173"
